import Assistance from './assistance'
import Background from './background'
import Blog from './blog'
import Catalog from './catalog'
import Login from './login'
import Payment from './payment'
import Card from './payment/card'
import AddCard from './payment/card/add'
import Cart from './payment/cart'
import Location from './payment/location'
import AddLocation from './payment/location/add'
import { Post1, Post2, Post3 } from './posts'
import Register from './register'

export { Background, Blog, Catalog, Login, Post1, Post2, Post3, Register, Assistance, Cart, Card, AddCard, Location, AddLocation, Payment }